### ISSUE TITLE
'DistributionalThesaurus' object has no attribute 'keys': is everything ok with the rdt model?

### ISSUE THREAD

**Issue by sadov-m** [nlpub/rdt#2]
Today I have tried to run the code situated at _https://github.com/nlpub/rdt/blob/master/dt.py_ and, unfortunately, this attempt was not successful.

I manually downloaded the rdt pickle model, installed all the dependencies and adapted some code from the file in order to make it work for **python 3**.

Here is what happened during running: after 25 seconds of running the code crashed saying that "_'DistributionalThesaurus' object has no attribute 'keys'_". This error message might mean that there is something wrong with rdt model:

1) either the **DistributionalThesaurus** object is uninitialized (the absense of the attribute 'keys' means that the __init__ function has not been run which is strange)
2) or there is something wrong with loading on **python 3** the model which was pickled using **python 2**. For loading I used python 3 library called pickle. The line responsible for loading is `pickle.load(open(dt_pkl_fpath, "rb"), encoding='bytes')`.

**Comment by dustalov** [comment]
Hello and thank you for your interest in this repository. I am pretty sure that your problem is caused to a too new version of [Gensim](https://radimrehurek.com/gensim/) that has its `Word2Vec`/`KeyedVectors` API changed. Please try using an older version of Gensim.

@alexanderpanchenko could you please remind us when have you created these pickled RDTs?

**Comment by dustalov** [comment]
Hello and thank you for your interest in this repository. I am pretty sure that your problem is caused by a too recent version of [Gensim](https://radimrehurek.com/gensim/) that has its `Word2Vec`/`KeyedVectors` API changed. Please try using a much older version of Gensim.

@alexanderpanchenko could you please remind us when have you created these pickled RDTs?

**Comment by sadov-m** [comment]
Hello @dustalov ,

Thank you for the answer but I have not understood what Gensim has to do with rdt. As far as I know, rdt does not use Gensim (it was not mentioned in the _requirements.txt_ file and it was not imported anywhere in the code). Am I missing something?

**Comment by dustalov** [comment]
Usually, you get quick answers here, but we are very busy these days. I am afraid I cannot help you until mid-February 2019.

**Comment by sadov-m** [comment]
@dustalov I will be glad to receive an answer if it is possible.

**Comment by dustalov** [comment]
@sadov-m thank you for your patience. I can return to this issue only on Monday.

**Comment by dustalov** [comment]
@sadov-m thank you for your patience. I can return to this issue only on Monday.

Just in case you need a word embeddings model based on RDT, you can download it on ZENODO: <https://zenodo.org/record/400631>.

**Comment by dustalov** [comment]
I added a model converter script `./convert_python3.py rdt.pkl` that outputs a file named `rdt.pkl.3`. You can use it instead of the original one. I do not like how the model fetching code is written, so currently make sure that the file name is still `rdt.pkl`.

**Comment by sadov-m** [comment]
Thank you for help! I will try to use it.
